DELETE http://localhost:8080/mbc/book-types/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyYyI6InNlIiwiZXhwIjoxNzU1MzU1NzYzLCJ1c2VybmFtZSI6Imlyd2FuLmRldiJ9.XDhYZnXBYCgHBDTg_atCy9UPxRm3gD1tNrGt8L_8Bd4

{
    "bookTypeCode": "ADV"
}