PUT http://localhost:8080/mbc/book-types/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyYyI6InNlIiwiZXhwIjoxNzU1MzUzMDg0LCJ1c2VybmFtZSI6Imlyd2FuLmRldiJ9.F9ZBMZGKddndSUoHmfFUxK02Hv8zZC49ihOHC91iKuk

{
    "bookTypeCode": "ADV",
    "bookTypeName": "Adventure"
}