GET http://localhost:8080/mbc/read-books/ISB12234/issbn?page=1&limit=10
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyYyI6InNlIiwiZXhwIjoxNzU1NTMzMDcwLCJ1c2VybmFtZSI6Imlyd2FuLmRldiJ9.6PU4WEEQYeINP4WTcjqaXzwAhwG-NJmK7P-YgNk9W84