GET http://localhost:8080/read-books/cf976b1f-e45d-43f3-a3d2-229845c42240/id
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyYyI6InNlIiwiaWQiOiIyNWRjZmQ3OC1jMGYyLTQ5NGEtYmU1MC0wYTk3MzY1YmFjMjgiLCJleHAiOjE3NTQ0NDk3MTZ9.MmIiSQC9N36YMeADpsPUrOe_-XeCWqlm9qTXUzYhXko