POST http://localhost:8080/mbc/books/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyYyI6InNlIiwiZXhwIjoxNzU1NDE2NDI2LCJ1c2VybmFtZSI6Imlyd2FuLmRldiJ9.C23xBDml1Qe-6BpvAyvMH1VHalYvLhMrphZJMbZX22k

{
    "issbn":"ISB181298",
    "title":"Filosofi Teras Cetakan 3",
    "numberOfPage":500,
    "description":"Build Human Habit for someday",
    "price":20.0,
    "publisher":"No",
    "authorName":"Now",
    "bookTypes":[
        {
            "bookTypeCode":""
        },
        {
            "bookTypeCode":"AV"
        }
    ] 
}