POST http://localhost:8080/mbc/books/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyYyI6InNlIiwiZXhwIjoxNzU1MTcxNDQ0LCJ1c2VybmFtZSI6Imlyd2FuLmRldiJ9.4hA0wpMBlptVlveDaIbZR5MQo-8T3yIrpECT1C5mB8c

{
    "issbn":"ISB12236",
    "title":"Atomic Habits 5",
    "numberOfPage":"700",
    "description":"Build Human Habit for someday",
    "price":20.0,
    "publisher":"No",
    "authorName":"Now",
    "bookTypes":[
        {
            "bookTypeCode":"ADV"
        }
    ] 
}