GET http://localhost:8080/mbc/books/?page=1&limit=10
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyYyI6InNlIiwiZXhwIjoxNzU1MDkxMzQxLCJ1c2VybmFtZSI6Imlyd2FuLmRldiJ9.YTvSnj7WT9wu_8qAPALO96Umxx_pZYfGvNxA598qI7A