GET http://localhost:8080/mbc/books/ISB12236/id
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyYyI6InNlIiwiZXhwIjoxNzU1MTc0MDY2LCJ1c2VybmFtZSI6Imlyd2FuLmRldiJ9.yJopXIOcWIz9-YQAiPPo2Yimk6F5EpKCcbUY_bCdY_U