GET http://localhost:8080/mbc/books/?page=1&limit=10
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyYyI6InNlIiwiZXhwIjoxNzU1NDI2MjU2LCJ1c2VybmFtZSI6Imlyd2FuLmRldiJ9.96JkIJwCVlulGWsuuaE9Yuq0OjLnQvzAtQUytmITFHs