PUT http://localhost:8080/mbc/books/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyYyI6InNlIiwiZXhwIjoxNzU1MTc1MzAxLCJ1c2VybmFtZSI6Imlyd2FuLmRldiJ9.J5keDQNEiDBtEes6FNRim3YHqfgCqLneiQUrafcY150

{
    "issbn":"ISB12236",
    "title":"Spiderman 5",
    //"numberOfPage":"700",
    "description":"Build Human to be spiderman"
    // "price":20.0,
    // "publisher":"No",
    // "authorName":"Now",
}