GET http://localhost:8080/mbc/status/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyYyI6InNlIiwiZXhwIjoxNzU1MDg0MDY5LCJ1c2VybmFtZSI6Imlyd2FuLmRldiJ9.VVD9AmaQc82bVOHWQZW5CDeOMo5rKKQ0lUJroSG5noY